name: Update the documentation if needed
on: [ pull_request ]
jobs:
  update-files:
    if: github.event.pull_request.base.repo.full_name == github.event.pull_request.head.repo.full_name
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          token: ${{ secrets.PAT }}
      - name: Update resources with Maven
        run: mvn -B process-resources
      - name: Update files if needed
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Automatically update versions
