name: Update documentation
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          token: ${{ github.token }}
      - name: Send pull-request
        run: |
          BRANCH_NAME="auto/update-files"
          echo "BRANCH_NAME: $BRANCH_NAME"
          echo "EVENT: ${{github.event}}"
          echo "GITHUB_REF: ${{github.event.pull_request.head.ref}}"
          echo "GITHUB_REPOSITORY: ${{github.event.pull_request.head.repo.full_name}}"
          echo "SECRET_PAT: ${{ secrets.PAT }}"


#      - name: Send pull-request
#        run: |
#          BRANCH_NAME="auto/update-files"
#
#          # Setup the committers identity.
#          git config user.email "david@pilato.fr"
#          git config user.name "David Pilato"
#
#          # Create a new feature branch for the changes.
#          git checkout -b $BRANCH_NAME
#
#          # Run the maven update.
#          mvn -B  generate-resources
#
#          # Commit the changes and push the feature branch to origin
#          git add .
#          git commit -m "Automatically update versions"
#          git push origin $BRANCH_NAME
#
#          # Store the PAT in a file that can be accessed by the
#          # GitHub CLI.
#          echo "${{ secrets.PAT }}" > token.txt
#
#          # Authorize GitHub CLI for the current repository and
#          # create a pull-requests containing the updates.
#          gh auth login --with-token < token.txt
#          gh pr create \
#            --body "" \
#            --title "Update all the files with new versions" \
#            --head "$BRANCH_NAME" \
#            --base "${{ github.event.pull_request.head.ref }}"
