name: Update documentation
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}
      - name: Update resources with Maven
        run: mvn -B process-resources
      - name: Update files if needed
        uses: stefanzweifel/git-auto-commit-action@v4
